/*
 * Doxey API
 * Generate personalized documents using doxey template language
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@floreysoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.floreysoft.doxey.invoke.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
