/*
 * Doxey API
 * Generate personalized documents using doxey template language
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@floreysoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.floreysoft.doxey.api;

import com.floreysoft.doxey.invoke.ApiException;
import java.io.File;
import com.floreysoft.doxey.model.Params;
import com.floreysoft.doxey.model.Params1;
import org.junit.Test;
import org.junit.Ignore;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * Convert the template document into a new document, given a Model
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void converterTest() throws ApiException {
        String fileId = null;
        String locale = null;
        String currency = null;
        String timezone = null;
        String format = null;
        Object model = null;
        File response = api.converter(fileId, locale, currency, timezone, format, model);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Convert the template document into a new document, given a Model
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void directConverterTest() throws ApiException {
        Params params = null;
        File response = api.directConverter(params);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Convert the template document into a multi documents based on the given number of models
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void zipConverterTest() throws ApiException {
        Params1 params = null;
        File response = api.zipConverter(params);

        // TODO: test validations
    }
    
}
